name: DonutOrder
version: '1.1'
main: de.elivb.donutOrder.Order
api-version: '1.21'
author: ᴇʟɪᴠʙ
description: ᴏʀᴅᴇʀ ᴘʟᴜɢɪɴ ʟɪᴋᴇ ᴅᴏɴᴜᴛꜱᴍᴘ
website: https://discord.gg/V3fcWZrccj
folia-supported: true
softdepend: [Vault]

permissions:
  order.use:
    default: true

  order.admin:
    default: op
    children:
      order.use: true